"""Removing Shipping Details From Order

Revision ID: 01d3c28f5cc8
Revises: 2133f248088e
Create Date: 2022-09-23 17:57:32.714109

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "01d3c28f5cc8"
down_revision = "2133f248088e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "order", "contact", ["contact_id"], ["id"])
    op.drop_column("order", "address2")
    op.drop_column("order", "address1")
    op.drop_column("order", "state")
    op.drop_column("order", "postal_code")
    op.drop_column("order", "city")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order", sa.Column("city", sa.VARCHAR(length=32), nullable=False))
    op.add_column(
        "order", sa.Column("postal_code", sa.VARCHAR(length=16), nullable=False)
    )
    op.add_column("order", sa.Column("state", sa.VARCHAR(length=2), nullable=False))
    op.add_column("order", sa.Column("address1", sa.VARCHAR(length=32), nullable=False))
    op.add_column("order", sa.Column("address2", sa.VARCHAR(length=32), nullable=True))
    op.drop_constraint(None, "order", type_="foreignkey")
    # ### end Alembic commands ###
