"""Adding Contact Model

Revision ID: 2133f248088e
Revises: 84ce5e55b294
Create Date: 2022-09-20 21:43:55.645574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2133f248088e'
down_revision = '84ce5e55b294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first', sa.String(length=32), nullable=False),
    sa.Column('last', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('order', sa.Column('contact_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order', 'contact', ['contact_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'contact_id')
    op.drop_table('contact')
    # ### end Alembic commands ###
