"""Merging Contact & Order Models

Revision ID: 42fd67085a8d
Revises: 01d3c28f5cc8
Create Date: 2022-09-23 20:34:54.268927

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "42fd67085a8d"
down_revision = "01d3c28f5cc8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contact")
    op.add_column("order", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("order", sa.Column("first", sa.String(length=32), nullable=False))
    op.add_column("order", sa.Column("last", sa.String(length=32), nullable=False))
    op.add_column("order", sa.Column("email", sa.String(length=32), nullable=False))
    op.add_column("order", sa.Column("phone", sa.String(length=32), nullable=False))
    op.drop_column("order", "address1")
    op.drop_column("order", "city")
    op.drop_column("order", "postal_code")
    op.drop_column("order", "address2")
    op.drop_column("order", "contact_id")
    op.drop_column("order", "state")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order", sa.Column("state", sa.VARCHAR(length=2), nullable=False))
    op.add_column("order", sa.Column("contact_id", sa.INTEGER(), nullable=False))
    op.add_column("order", sa.Column("address2", sa.VARCHAR(length=32), nullable=True))
    op.add_column(
        "order", sa.Column("postal_code", sa.VARCHAR(length=16), nullable=False)
    )
    op.add_column("order", sa.Column("city", sa.VARCHAR(length=32), nullable=False))
    op.add_column("order", sa.Column("address1", sa.VARCHAR(length=32), nullable=False))
    op.drop_column("order", "phone")
    op.drop_column("order", "email")
    op.drop_column("order", "last")
    op.drop_column("order", "first")
    op.drop_column("order", "created_at")
    op.create_table(
        "contact",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("first", sa.VARCHAR(length=32), nullable=False),
        sa.Column("last", sa.VARCHAR(length=32), nullable=False),
        sa.Column("email", sa.VARCHAR(length=32), nullable=False),
        sa.Column("phone", sa.VARCHAR(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###
