"""Need 128 Bytes For Hash

Revision ID: 549503bbab1c
Revises: 9932300e7303
Create Date: 2022-10-09 20:57:48.507613

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "549503bbab1c"
down_revision = "9932300e7303"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "hash", ["id"])
    op.create_unique_constraint(None, "item", ["id"])
    op.create_unique_constraint(None, "order", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "order", type_="unique")
    op.drop_constraint(None, "item", type_="unique")
    op.drop_constraint(None, "hash", type_="unique")
    # ### end Alembic commands ###
