"""Redesign Of Models

Revision ID: 63dde2052a25
Revises: 20c22d11c6a8
Create Date: 2022-10-01 23:48:25.028913

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "63dde2052a25"
down_revision = "20c22d11c6a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hash", sa.Column("item_id", sa.Integer(), nullable=False))
    op.drop_constraint("hash_order_id_fkey", "hash", type_="foreignkey")
    op.create_foreign_key(None, "hash", "item", ["item_id"], ["id"])
    op.drop_column("hash", "order_id")
    op.add_column("order", sa.Column("hash_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "order", "hash", ["hash_id"], ["id"])
    op.drop_column("order", "fulfilled")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order",
        sa.Column("fulfilled", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "order", type_="foreignkey")
    op.drop_column("order", "hash_id")
    op.add_column(
        "hash", sa.Column("order_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "hash", type_="foreignkey")
    op.create_foreign_key("hash_order_id_fkey", "hash", "order", ["order_id"], ["id"])
    op.drop_column("hash", "item_id")
    # ### end Alembic commands ###
