""" Initial Migration

Revision ID: 7547cf2cc127
Revises:
Create Date: 2022-09-26 15:13:18.171778

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7547cf2cc127"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "size", sa.Enum("XS", "S", "M", "L", "XL", name="size"), nullable=False
        ),
        sa.Column("inventory", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "order",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("first", sa.String(length=32), nullable=False),
        sa.Column("last", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=32), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("fulfilled", sa.Boolean(), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order")
    op.drop_table("item")
    # ### end Alembic commands ###
