"""Making Store Use Names Instead Of PK

Revision ID: 9932300e7303
Revises: 63dde2052a25
Create Date: 2022-10-02 01:32:00.598295

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9932300e7303"
down_revision = "63dde2052a25"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hash", sa.Column("value", sa.String(length=64), nullable=True))
    op.drop_column("hash", "val")
    op.add_column("item", sa.Column("name", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("item", "name")
    op.add_column(
        "hash",
        sa.Column("val", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    )
    op.drop_column("hash", "value")
    # ### end Alembic commands ###
